### ISSUE TITLE
Implement a way to define lists of components

### ISSUE THREAD

**Issue by tigris** [mdub/config_mapper#6]
We would like a way to define lists. In my head, the config would look like this:

```yaml
people:
-
  name: danial pearce
  awesomeness: 10
  preferences:
    drink: beer
    food: burgers
-
  name: fred
  awesomeness: 2
  preferences:
    drink: water
```

And the model might look something like this:

```ruby
class Config < ConfigMapper::ConfigStruct
  component_list :people do
    attribute :name, String
    attribute :awesomeness, Integer, default: 0
    component_dict :preferences do
      attribute :drink, String
      attribute :food, String, default: "parmas"
    end
  end
end
```

Which would map to PORs like so:

```json
{
  "people": [
    { "name": "danial pearce", "awesomeness": 10, "preferences": { "drink": "beer", "food": "burgers" } },
    { "name": "fred", "awesomeness": 2, "preferences": { "drink": "wine", "food": "parmas" } },
  ]
}
```

I think doing the above is currently possible by creating a `Types::People`, and using `component :people, type: Types::People` although I've not yet tried. I think the above would be a nicer solution in the long run, as the entire config definition would be in 1 place instead of spread out across multiple types, where the "type" also has other stuff mingled in with it and doesn't read quite as nice as a simple config definition.
